apluslms_shepherd/courses/models.py
from apluslms_shepherd.extensions import db
from apluslms_shepherd.groups.models import gc_table


class CourseInstance(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    course_key = db.Column(db.String(50), nullable=False)
    name = db.Column(db.String(50), default='')
    owners = db.relationship("Group", secondary=gc_table, backref=db.backref('courses', lazy='dynamic'))
    instance_key = db.Column(db.String(50), nullable=False)
    origin = db.Column(db.String(255), db.ForeignKey('git_repository.origin'), default='')
    secret_token = db.Column(db.String(127))
    config_filename = db.Column(db.String(127))
    branch = db.Column(db.String, default='master')

apluslms_shepherd/courses/forms.py
from wtforms import Form, StringField, validators, SelectField


class CourseForm(Form):
    course_key = StringField('Course Key', [validators.InputRequired(), validators.Length(max=50)])
    instance_key = StringField('Instance Key', [validators.InputRequired(), validators.Length(max=50)])
    name = StringField('Course Name', [validators.InputRequired(), validators.Length(min=1, max=50)])
    origin = StringField('Git Repo', [validators.InputRequired(), validators.Length(max=255)])
    secret_token = StringField('Secret Token', [validators.length(max=127), validators.optional(True)],
                               render_kw={
                                   "placeholder": "If no secret token set for GitHub/Gitlab webhook, leave this empty."
                               })

    branch = StringField('Branch', [validators.InputRequired(), validators.Length(max=50)])
    config_filename = StringField('Roman Config File', [validators.length(max=127), validators.optional(True)],
                                  render_kw={"placeholder": "To use default filename(course.yml), leave this empty."})
    # The options of the identity group which has the permission to create new courses
    # and the current user is the member of
    identity = SelectField('Identity', choices=[(-1, "---")], coerce=int)
    # The options of the group that owns the course
    owner_group = SelectField('Owner Group', choices=[(-1, "---")], coerce=int)


class CourseEditForm(Form):
    key = StringField('Course Key', [validators.InputRequired(), validators.Length(max=50)])
    name = StringField('Course Name', [validators.InputRequired(), validators.Length(min=1, max=50)])
    origin = StringField([validators.Optional(), validators.Length(max=255)])
    identity = SelectField('Identity', choices=[(-1, "---")], coerce=int)

apluslms_shepherd/__init__.py
from flask import Flask, request, session, redirect, flash
from flask_login import current_user
from flask_lti_login import lti, lti_login_authenticated
from flask_migrate import Migrate
from flask_principal import Principal, identity_loaded, RoleNeed, UserNeed

from apluslms_shepherd import config
from apluslms_shepherd.extensions import celery, db, make_celery
from apluslms_shepherd.groups.models import PermType

__version__ = '0.1'


def create_app():
    app = Flask(__name__)
    app.config.from_object(config.DevelopmentConfig)
    # adds jinja2 support for break and continue in loops
    app.jinja_env.add_extension('jinja2.ext.loopcontrols')
    with app.app_context():
        from apluslms_shepherd.auth.models import write_user_to_db, login_manager
        from apluslms_shepherd.views import main_bp
        from apluslms_shepherd.auth.views import auth_bp
        from apluslms_shepherd.courses.views import course_bp
        from apluslms_shepherd.build.views import build_log_bp
        from apluslms_shepherd.webhooks.views import webhooks_bp
        from apluslms_shepherd.groups.views import groups_bp
        from apluslms_shepherd.repos.views import repo_bp
        login_manager.init_app(app=app)
        db.init_app(app=app)
        migrate = Migrate(app, db, render_as_batch=True)
        lti_login_authenticated.connect(write_user_to_db)
        # Flask-Principal: ---  Setup ------------------------------------
        principals = Principal(app)
        principals.init_app(app)
        # -----------------------------------------------------------------
        app.register_blueprint(main_bp)
        app.register_blueprint(build_log_bp)
        app.register_blueprint(course_bp)
        app.register_blueprint(lti)
        app.register_blueprint(auth_bp)
        app.register_blueprint(webhooks_bp)
        app.register_blueprint(groups_bp)
        app.register_blueprint(repo_bp)
        
        # Add info to the Identity instance
        @identity_loaded.connect_via(app)
        def on_identity_loaded(sender, identity):
            # Set the identity user object
            identity.user = current_user

            # Add the UserNeed to the identity
            if hasattr(current_user, 'id'):
                identity.provides.add(UserNeed(current_user.id))

            # Update the identity with the role that the user provides
            if hasattr(current_user, 'roles'):
                for role in current_user.roles.split(','):
                    identity.provides.add(RoleNeed(role))

            app.logger.info(identity)


        # Handle HTTP 403 error
        @app.errorhandler(403)
        def access_forbidden(e):
            session['redirected_from'] = request.url
            flash('Access Forbidden')
            return redirect('/')
        
    return app

apluslms_shepherd/builder/__init__.py
from __future__ import absolute_import
from celery import Celery
from .config import CelerySettingDev

app = Celery(
    CelerySettingDev.CELERY_NAME,
    broker=CelerySettingDev.CELERY_BROKER_ADDRESS,
    backend=CelerySettingDev.CELERY_BROKER_ADDRESS,
    include=['apluslms_shepherd.builder.tasks'])

apluslms_shepherd/courses/views.py
import logging
from json import dumps

from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, abort, Response
from flask_login import login_required, current_user
from sqlalchemy.exc import SQLAlchemyError

from apluslms_shepherd.auth.models import User
from apluslms_shepherd.build.models import BuildLog
from apluslms_shepherd.config import DevelopmentConfig
from apluslms_shepherd.courses.forms import CourseForm
from apluslms_shepherd.courses.models import CourseInstance, db
from apluslms_shepherd.groups.forms import GroupForm
from apluslms_shepherd.groups.models import Group, PermType, CreateCoursePerm, \
    ManageCoursePerm, CourseOwnerType
from apluslms_shepherd.groups.utils import group_slugify, PERMISSION_LIST, \
    role_permission, course_instance_create_perm, \
    course_instance_admin_perm
from apluslms_shepherd.repos.models import GitRepository
from apluslms_shepherd.repos.tasks.tasks import clean_unused_repo, generate_deploy_key

course_bp = Blueprint('courses', __name__, url_prefix='/courses/')
logger = logging.getLogger(__name__)


@course_bp.route('', methods=['GET'])
@login_required
@role_permission.require(http_exception=403)
def list_course():
    all_courses = CourseInstance.query.all()
    return render_template('courses/course_list.html', user=current_user, courses=all_courses)


@course_bp.route('create/', methods=['GET', 'POST'])
@login_required
@role_permission.require(http_exception=403)
@course_instance_create_perm
def add_course(**kwargs):
    if 'identity_groups' in kwargs:
        identity_groups = kwargs['identity_groups']
    else:
        identity_groups = Group.query.filter(Group.members.any(id=current_user.id),
                                             Group.permissions.any(type=PermType.courses)).all()
    owner_groups = Group.query.filter(Group.members.any(id=current_user.id)).all()
    form = CourseForm(request.form)
    form.identity.choices += [(g.id, group_slugify(g.name, g.parent)) for g in identity_groups]
    form.owner_group.choices = [(g.id, group_slugify(g.name, g.parent)) for g in owner_groups]
    group_form = GroupForm(request.form)
    group_form.permissions.choices = [v for v in PERMISSION_LIST if v != ('courses', 'create courses')]

    if request.method == 'POST' and form.validate():
        course_perm = CreateCoursePerm.query.filter_by(group_id=form.identity.data).one_or_none()
        if not course_perm:
            flash('Please choose a valid identity')
            return redirect(url_for('.add_course'))

        if not course_perm.pattern_match(form.course_key.data.upper()):
            flash('The course key does not match the naming rule ')
            return redirect(url_for('.add_course'))
        exists = CourseInstance.query.filter(CourseInstance.course_key == form.course_key.data.upper(),
                                             CourseInstance.instance_key == form.instance_key.data).first()
        if exists:
            flash('Course key %s and instance key %s already exists.' % (
                form.course_key.data.upper(), form.instance_key.data))
        else:
            repository = GitRepository.query.filter_by(origin=form.origin.data).first()
            if repository is None:
                new_repository = GitRepository(origin=form.origin.data)
                new_repository.save()
                # Start generating key pair for this repository.
                generate_deploy_key.apply_async(args=[DevelopmentConfig.REPO_KEYS_PATH, form.origin.data])
            new_course = CourseInstance(course_key=form.course_key.data.upper(),
                                        instance_key=form.instance_key.data,
                                        branch=form.branch.data,
                                        origin=form.origin.data,
                                        secret_token=None if form.secret_token.data == '' else form.secret_token.data,
                                        config_filename=None if form.config_filename.data == '' else form.secret_token.data,
                                        name=form.name.data)
            owner_group = Group.query.filter(Group.id == form.owner_group.data).one_or_none()
            new_course.owners.append(owner_group)
            course_admin_perm = ManageCoursePerm(course_instance=new_course, group=owner_group,
                                                 type=CourseOwnerType.admin)
            db.session.add(new_course)
            db.session.commit()
            db.session.add(course_admin_perm)
            db.session.commit()
            flash('New course added.')
        return redirect('/courses/')
    return render_template('courses/course_create.html', form=form, group_form=group_form)


@course_bp.route('edit/<course_key>/<instance_key>/', methods=['GET', 'POST'])
@login_required
@role_permission.require(http_exception=403)
@course_instance_admin_perm
def edit_course(course_key, instance_key, **kwargs):
    # Get course from db
    course = CourseInstance.query.filter_by(course_key=course_key, instance_key=instance_key)
    origin_prev = course.first().origin
    form = CourseForm(request.form, obj=course.first())
    # Get the options of identity groups
    identity_groups = Group.query.filter(Group.members.any(id=current_user.id),
                                         Group.permissions.any(type=PermType.courses)).all()
    form.identity.choices += [(g.id, group_slugify(g.name, g.parent)) for g in identity_groups]
    # The label is changes according to whether user is edit a course or creating a course,
    # When editing a course, it should be changed to follows, or it will be "First instance origin"
    if request.method == 'POST' and form.validate():
        # Check whether the course key match the naming rule
        course_perm = CreateCoursePerm.query.filter_by(group_id=form.identity.data).one_or_none()
        if not course_perm:
            flash('Please choose a valid identity group')
            return redirect(url_for('.edit_course', course_key=course_key, instance_key=instance_key))
        if not course_perm.pattern_match(form.course_key.data.upper()):
            flash('The course key does not match the naming rule: {}'.format(course_perm.pattern))
            return redirect(url_for('.edit_course', course_key=course_key))
        origin_new = form.origin.data
        course.update(dict(
            course_key=form.course_key.data.upper(),
            instance_key=form.instance_key.data,
            branch=form.instance_key.data,
            # origin=origin_new,
            secret_token=None if form.secret_token.data == '' else form.secret_token.data,
            config_filename=None if form.config_filename.data == '' else form.secret_token.data,
            name=form.name.data
        ))
        flash('Course edited.')
        db.session.commit()
        logger.info('Course edited')
        # Check if has change on origin
        if origin_new != origin_prev:
            # Create new, is this new repo is not in db yet.
            if GitRepository.query.filter_by(origin=origin_new).one_or_none() is None:
                logger.info('This new repository is not exists in database,add it to database')
                new_repo = GitRepository(origin=origin_new)
                new_repo.save()
                course.update(dict(origin=origin_new))
                generate_deploy_key.apply_async(args=[DevelopmentConfig.REPO_KEYS_PATH, origin_new])
            # Delete old, if old repo becomes an orphan repository.
            if CourseInstance.query.filter_by(origin=origin_prev).one_or_none() is None:
                logger.info(
                    'This edit makes the repository %s becomes an orphan repository, cleaning this repository.' % origin_prev)
                clean_unused_repo.delay(origin_prev)
        return redirect('/courses/')
    return render_template('courses/course_edit.html', form=form)


@course_bp.route('delete/<course_key>/<instance_key>/', methods=['POST'])
@login_required
@role_permission.require(http_exception=403)
@course_instance_admin_perm
def del_course_instance(course_key, instance_key, **kwargs):
    course_instance = kwargs['course_instance']
    repo = GitRepository.query.filter_by(origin=course_instance.origin).one_or_none()
    repo_number_before_del = 0
    if repo is None:
        logger.error("No matching repo in the database")
    else:
        repo_number_before_del = repo.courses.count()
    db.session.delete(course_instance)
    BuildLog.query.filter_by(course_id=course_instance.id).delete()
    db.session.commit()
    if repo_number_before_del == 1:
        # start delete celery task
        logger.info(
            'The repository %s becomes an orphan repository after deleting the course instance, cleaning this repository.' % course_instance.origin)
        clean_unused_repo.delay(course_instance.origin)
    flash('Instance with key: ' + instance_key + ' belonging to course with key: ' + course_key + ' has been deleted.')
    return redirect('/courses/')


# -------------------------------------------------------------------------------------------------#
# Ownership management

@course_bp.route('<course_key>/<instance_key>/owners/', methods=['GET'])
@login_required
@role_permission.require(http_exception=403)
def owners_list(course_key, instance_key, **kwargs):
    """Get all the owner groups of a course  
    """
    # groups = (db.session.query(Group) 
    #                     .join(CourseInstance.owners)
    #                     .filter(CourseInstance.course_key == course_key,
    #                             CourseInstance.instance_key == instance_key).all())
    perms = (db.session.query(ManageCoursePerm)
             .join(ManageCoursePerm.course_instance)
             .filter(CourseInstance.course_key == course_key,
                     CourseInstance.instance_key == instance_key).all())

    group_array = []

    for perm in perms:

apluslms_shepherd/repos/views.py
import logging

from flask import Blueprint, render_template
from flask_login import login_required, current_user

from apluslms_shepherd.groups.utils import role_permission
from apluslms_shepherd.repos.models import GitRepository

repo_bp = Blueprint('repos', __name__, url_prefix='/repos/')
logger = logging.getLogger(__name__)


@repo_bp.route('', methods=['GET'])
@login_required
@role_permission.require(http_exception=403)
def list_repos():
    all_repos = GitRepository.query.all()
    return render_template('repos/repo_list.html', user=current_user, repos=all_repos)

apluslms_shepherd/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from apluslms_shepherd.build.models import Build
from apluslms_shepherd.courses.models import CourseInstance

main_bp = Blueprint('main', __name__)


class FrontendBuild(object):
    def __init__(self, course_id, number, course_key, instance_key, result):
        self.course_id = course_id
        self.instance_key = instance_key
        self.course_key = course_key
        self.number = number
        self.current_result = None if result is None else result.name


@main_bp.route('/', methods=['GET'])
@login_required
def main_page():
    instances = CourseInstance.query.all()
    sorted_build_entries = Build.query.order_by(Build.number.desc())
    newest_builds = [
        FrontendBuild(course_id=instance.id,
                      instance_key=instance.instance_key,
                      course_key=instance.course_key,
                      number=0 if len(sorted_build_entries.filter_by(course_id=instance.id).all()) is 0
                      else sorted_build_entries.filter_by(course_id=instance.id).first().number,
                      result=None if len(sorted_build_entries.filter_by(course_id=instance.id).all()) is 0
                      else sorted_build_entries.filter_by(course_id=instance.id).first().result,
                      )
        for instance in instances
    ]
    return render_template('main.html', user=current_user, instances=newest_builds)

apluslms_shepherd/templates/_formhelpers.html
{% macro render_field(field) %}
    <dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
            <ul class=errors>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </dd>
{% endmacro %}

apluslms_shepherd/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    {% block head %}
    {% endblock %}
    <title>
        {% block title %}
            Gitmanager
        {% endblock %}
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#">
        <img src="https://avatars3.githubusercontent.com/u/29550159?s=200&v=4" width="35" height="35"
             class="d-inline-block align-top" alt="">
        <span class="text-center font-weight-bold"> Shepherd</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/courses/">Courses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/courses/create/">New Course</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="/groups/">Groups</a>
            </li>
            <!-- <li class="nav-item">
                    <a class="nav-link" href="/groups/create/">Create group</a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('groups.list_my_groups')}}">My groups</a>
        </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('repos.list_repos') }}">My Repos</a>
            </li>
        </ul>
    </div>
    <button class="btn btn-outline-danger" onclick="location.href='/auth/logout/'">Logout</button>
</nav>
<div class="container text-center">
    {% for message in get_flashed_messages() %}
        <div class="badge-info">{{ message }}</div>
    {% endfor %}
</div>
{% block body %}
    <h1>MOI</h1>
{% endblock %}
</body>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block scripts %}
{% endblock %}
</html>

apluslms_shepherd/templates/course_list.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}
{% block title %}
    All Courses
{% endblock %}

{% block body %}
    <div class="container text-center">
        <div>User id:{{ user.id }}</div>
        course_list.html
        <table class="text-center table">
            <caption>Courses</caption>
            <thead>
            <tr>
                <th scope="col">Course Key</th>
                <th scope="col">Instance Key</th>
                <th scope="col">Name</th>
                <th scope="col">Identity</th>
                <th scope="col">Git</th>
                <th scope="col">Operations</th>
            </tr>
            </thead>
            <tbody>
            {% for each in courses %}
                <tr>
                    <td>{{ each.course_key }}</td>
                    <td>{{ each.instance_key }}</td>
                    <td>{{ each.name }}</td>
                    <td>
                        <ul style="list-style-type: none">
                            {% for owner in each.owners %}
                                <li>
                                    {{ owner.name }}
                                </li>
                            {% endfor %}

                        </ul>


                    </td>
                    <td>{{ each.git_origin }}:{{ each.branch }}</td>
                    <td>
                        <form method="post" action="/courses/delete/{{ each.course_key }}/{{ each.instance_key }}/">
{#                            <a class=" btn btn-outline-primary" data-toggle="collapse" href="#{{ each.key }}"#}
{#                               role="button" aria-expanded="false" aria-controls="collapseExample">#}
{#                                View instances#}
{#                            </a>#}
                            <button type="button" class="btn btn-outline-primary"
                                    onclick="location.href='/courses/edit/{{ each.course_key }}/{{ each.instance_key }}/'">Edit
                            </button>
                            <button type="button" class="btn btn-outline-primary"
                                    onclick="location.href='/courses/create/?course={{ each.course_key }}&instance={{ each.instance_key }}'">Duplicate
                            </button>
                            <button type="button" class="btn btn-outline-primary owner_groups" 
                                    data-course={{each.course_key}} data-instance={{each.instance_key}}>Owner groups
                            </button>
                            <button type="submit" class="btn btn-outline-danger are-you-sure">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    
<div id="content">
        {% block content %}
        {% include 'groups/owner_groups.html' %}
        {% endblock %}
</div>
{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="{{ url_for('static', filename='owner_groups.js') }}"></script>
<script src="../static/are_you_sure.js"></script>
{% endblock %}

apluslms_shepherd/templates/main.html
{% extends 'base.html' %}    <div class="container text-center">
        <div>User id:{{ user.id }}</div>
{% block title %}
    Welcome to Shepherd
{% endblock %}

{% block body %}
    <div class="container text-center">
    <div>Hi, {{ user.display_name }} {{ user.sorting_name }}!</div>
            <div>Your user ID is :{{ user.id }}</div>
                    <table class="text-center table">
                                <caption>Instances Build State</caption>
                    <thead>
                    <tr>
                        <th scope="col">Course Key</th>
                        <th scope="col">Instance Key</th>
                        <th scope="col">Build Number</th>
                        <th scope="col">Shepherd Step</th>
                        <th scope="col">Roman Step</th>
                         <th scope="col">State</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ins in instances %}
                        <tr onclick="window.location.href='/logs/{{ ins.course_id }}/'">
                            <td>{{ ins.course_key }}</td>
                            <td>{{ ins.instance_key }}</td>
                            <td class="table-number" id="{{ ins.course_id }}">{{ ins.number }}</td>
                            <td class="table-step" id="{{ ins.course_id }}">Not Running</td>
                            <td class="table-roman-step" id="{{ ins.course_id }}">Not Running</td>
                            <td class="table-state" id="{{ ins.course_id }}">{{ ins.current_result }}</td>

                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"></script>
    <script src="../static/socketio.js"></script>
{% endblock %}

apluslms_shepherd/templates/repo_list.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}
{% block title %}
    All Courses
{% endblock %}

{% block body %}
    <div class="container text-center">
        <div>User id:{{ user.id }}</div>
        course_list.html
        <table class="text-center table">
            <caption>Repositories</caption>
            <thead>
            <tr>
                <th scope="col">Git origin</th>
                <th scope="col">Public Key</th>
                <th scope="col">Courses</th>
            </tr>
            </thead>
            <tbody>
            {% for each in repos %}
                <tr>
                    <td>{{ each.origin }}</td>
                    <td>{{ each.public_key }}</td>
                    <td>
                        <ul style="list-style-type: none">
                            {% for each_course in each.courses %}
                                <li> {{ each_course.name }}</li>
                            {% endfor %}
                        </ul>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div id="content">
        {% block content %}
            {% include 'groups/owner_groups.html' %}
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="{{ url_for('static', filename='owner_groups.js') }}"></script>
    <script src="../static/are_you_sure.js"></script>
{% endblock %}