apluslms_shepherd/courses/models.py
from apluslms_shepherd.extensions import db
from apluslms_shepherd.groups.models import gc_table


class CourseInstance(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    course_key = db.Column(db.String(50), nullable=False)
    name = db.Column(db.String(50), default='')
    owners = db.relationship("Group", secondary=gc_table, backref=db.backref('courses', lazy='dynamic'))
    instance_key = db.Column(db.String(50), nullable=False)
    origin = db.Column(db.String(255), db.ForeignKey('git_repository.origin'), default='')
    secret_token = db.Column(db.String(127))
    config_filename = db.Column(db.String(127))
    branch = db.Column(db.String, default='master')

apluslms_shepherd/courses/forms.py
from wtforms import Form, StringField, validators, SelectField


class CourseForm(Form):
    course_key = StringField('Course Key', [validators.InputRequired(), validators.Length(max=50)])
    instance_key = StringField('Instance Key', [validators.InputRequired(), validators.Length(max=50)])
    name = StringField('Course Name', [validators.InputRequired(), validators.Length(min=1, max=50)])
    origin = StringField('Git Repo', [validators.InputRequired(), validators.Length(max=255)])
    secret_token = StringField('Secret Token', [validators.length(max=127), validators.optional(True)],
                               render_kw={
                                   "placeholder": "If no secret token set for GitHub/Gitlab webhook, leave this empty."
                               })

    branch = StringField('Branch', [validators.InputRequired(), validators.Length(max=50)])
    config_filename = StringField('Roman Config File', [validators.length(max=127), validators.optional(True)],
                                  render_kw={"placeholder": "To use default filename(course.yml), leave this empty."})
    # The options of the identity group which has the permission to create new courses
    # and the current user is the member of
    identity = SelectField('Identity', choices=[(-1, "---")], coerce=int)
    # The options of the group that owns the course
    owner_group = SelectField('Owner Group', choices=[(-1, "---")], coerce=int)


class CourseEditForm(Form):
    key = StringField('Course Key', [validators.InputRequired(), validators.Length(max=50)])
    name = StringField('Course Name', [validators.InputRequired(), validators.Length(min=1, max=50)])
    origin = StringField([validators.Optional(), validators.Length(max=255)])
    identity = SelectField('Identity', choices=[(-1, "---")], coerce=int)

apluslms_shepherd/__init__.py
from flask import Flask, request, session, redirect, flash
from flask_login import current_user
from flask_lti_login import lti, lti_login_authenticated
from flask_migrate import Migrate
from flask_principal import Principal, identity_loaded, RoleNeed, UserNeed

from apluslms_shepherd import config
from apluslms_shepherd.extensions import celery, db, make_celery
from apluslms_shepherd.groups.models import PermType

__version__ = '0.1'


def create_app():
    app = Flask(__name__)
    app.config.from_object(config.DevelopmentConfig)
    # adds jinja2 support for break and continue in loops
    app.jinja_env.add_extension('jinja2.ext.loopcontrols')
    with app.app_context():
        from apluslms_shepherd.auth.models import write_user_to_db, login_manager
        from apluslms_shepherd.views import main_bp
        from apluslms_shepherd.auth.views import auth_bp
        from apluslms_shepherd.courses.views import course_bp
        from apluslms_shepherd.build.views import build_log_bp
        from apluslms_shepherd.webhooks.views import webhooks_bp
        from apluslms_shepherd.groups.views import groups_bp
        from apluslms_shepherd.repos.views import repo_bp
        login_manager.init_app(app=app)
        db.init_app(app=app)
        migrate = Migrate(app, db, render_as_batch=True)
        lti_login_authenticated.connect(write_user_to_db)
        # Flask-Principal: ---  Setup ------------------------------------
        principals = Principal(app)
        principals.init_app(app)
        # -----------------------------------------------------------------
        app.register_blueprint(main_bp)
        app.register_blueprint(build_log_bp)
        app.register_blueprint(course_bp)
        app.register_blueprint(lti)
        app.register_blueprint(auth_bp)
        app.register_blueprint(webhooks_bp)
        app.register_blueprint(groups_bp)
        app.register_blueprint(repo_bp)
        
        # Add info to the Identity instance
        @identity_loaded.connect_via(app)
        def on_identity_loaded(sender, identity):
            # Set the identity user object
            identity.user = current_user

            # Add the UserNeed to the identity
            if hasattr(current_user, 'id'):
                identity.provides.add(UserNeed(current_user.id))

            # Update the identity with the role that the user provides
            if hasattr(current_user, 'roles'):
                for role in current_user.roles.split(','):
                    identity.provides.add(RoleNeed(role))

            app.logger.info(identity)


        # Handle HTTP 403 error
        @app.errorhandler(403)
        def access_forbidden(e):
            session['redirected_from'] = request.url
            flash('Access Forbidden')
            return redirect('/')
        
    return app

apluslms_shepherd/builder/__init__.py
from __future__ import absolute_import
from celery import Celery
from .config import CelerySettingDev

app = Celery(
    CelerySettingDev.CELERY_NAME,
    broker=CelerySettingDev.CELERY_BROKER_ADDRESS,
    backend=CelerySettingDev.CELERY_BROKER_ADDRESS,
    include=['apluslms_shepherd.builder.tasks'])

apluslms_shepherd/groups/views.py
import logging
from json import dumps

from flask import Blueprint, render_template, url_for, redirect, request, flash, \
    Response, abort
from flask import jsonify
from flask_login import login_required, current_user

from apluslms_shepherd.auth.models import User
from apluslms_shepherd.courses.models import CourseInstance
from apluslms_shepherd.groups.forms import GroupForm
from apluslms_shepherd.groups.models import db, Group, PermType, GroupPermission, \
    CreateGroupPerm, CreateCoursePerm
from apluslms_shepherd.groups.utils import group_slugify, slugify, query_end_group, \
    role_permission, subgroup_create_perm, group_manage_perm, parent_group_check

logging.basicConfig(level=logging.DEBUG)

groups_bp = Blueprint('groups', __name__, url_prefix='/groups')


# -------------------------------------------------------------------------------------------------#
# Group listing 

@groups_bp.route('/', methods=['GET'])
@login_required
@role_permission.require(http_exception=403)
def list_all_groups():
    """Listing all the groups in the database
    """
    title = "Group list"
    roots = Group.query.filter_by(parent_id=None).all()
    return render_template('groups/group_list.html', title=title, user=current_user,
                           roots=roots, node=None)


@groups_bp.route('<group_id>/subgroups/', methods=['GET'])
@login_required
@role_permission.require(http_exception=403)
def list_subgroups(group_id):
    """Listing all the subgroups of a group
    """
    group = db.session.query(Group).filter_by(id=group_id).one_or_none()
    if group is None:
        flash('There is no such group')
        return redirect(url_for('groups.list_my_groups'))

    # roots = Group.query.filter_by(parent_id=group.id).all()
    roots = group.children
    title = 'Group: ' + group_slugify(group.name, group.parent)
    return render_template('groups/group_list.html', title=title, user=current_user,
                           roots=roots, node=group)


@groups_bp.route('/my_groups/', methods=['GET'])
@login_required
@role_permission.require(http_exception=403)
def list_my_groups():
    """Listing the groups which the current user is a member of
    """
    title = "My Groups"
    groups = Group.query.join(Group.members).filter(User.id == current_user.id).all()
    group_slugs = [group_slugify(g.name, g.parent) for g in groups]
    return render_template('groups/my_groups.html', title=title, user=current_user,
                           groups=zip(groups, group_slugs), PermType=PermType)


# -------------------------------------------------------------------------------------------------#
# Group Create

def new_group_to_db(group_name, parent_group, form):
    """The function creates a new group and add it to the database
    """
    # Create a new Group instance
    if parent_group:
        new_group = Group(name=group_name, parent_id=parent_group.id)
    else:
        new_group = Group(name=group_name, parent_id=None)

    # Add the permissions to the group
    selected_perms = form.permissions.data
    for name, perm_type in PermType.__members__.items():
        if name in selected_perms:
            perm = db.session.query(GroupPermission).filter(
                GroupPermission.type == perm_type).first()
            if not perm:
                perm = GroupPermission(type=perm_type)
            new_group.permissions.append(perm)

    # If the group is a root group OR the group is permitted to manage itself
    if new_group.parent_id is None or 'self_admin' in selected_perms:
        new_group.self_admin = True
    else:
        new_group.self_admin = False

    # If the group can create courses, create CreateCoursePerm object
    if 'courses' in selected_perms:
        course_prefix = form.course_prefix.data.upper()
        course_pattern = course_prefix + '-[A-Za-z][0-9][0-9][0-9][0-9]'
        course_perm = CreateCoursePerm(group=new_group, pattern=course_pattern)
        db.session.add(course_perm)

    # Default to set the creator as a member of the group    
    new_group.members.append(current_user)
    db.session.add(new_group)

    return new_group


@groups_bp.route('create/', methods=['GET', 'POST'])
@login_required
@role_permission.require(http_exception=403)
def create_group():
    """Create a new group by giving a parent path
    """
    form = GroupForm(request.form)
    if request.method == 'POST' and form.validate():
        flash(form.data)
        # Slugify the new group name and get its parent
        group_name = slugify(form.name.data, separator='_')
        parent_group = query_end_group(form.parent_path.data)

        # Check whether the new group can be created
        if not parent_group_check(group_name, parent_group):
            return redirect(url_for('.create_group'))

        # Add the group to the database
        _ = new_group_to_db(group_name, parent_group, form)
        try:
            db.session.commit()
            flash('The new group is added, and you are set as a member of the new group')
            return redirect(url_for('.list_my_groups'))
        except:
            db.session.rollback()
            flash('Could not create the group')

    return render_template('groups/group_create.html', form=form, parent=None)


@groups_bp.route('<group_id>/create/', methods=['GET', 'POST'])
@login_required
@role_permission.require(http_exception=403)
@subgroup_create_perm
def create_subgroup(group_id, **kwargs):
    """Create a subgroup by giving the id of a parent group
    """
    if 'group' in kwargs:
        parent_group = kwargs['group']
    else:
        parent_group = db.session.query(Group).filter_by(id=group_id).one_or_none()

    form = GroupForm(request.form)

    if request.method == 'POST' and form.validate():
        # Group name should not be empty
        if form.name.data == '':
            flash('The group name can not be empty!')
            return redirect(url_for('.create_subgroup', group_id=group_id))

        group_name = slugify(form.name.data, separator='_')
        if group_name in [g.name for g in parent_group.children]:
            flash('The group already exists.')
            return redirect(url_for('.create_subgroup', group_id=group_id))

        _ = new_group_to_db(group_name, parent_group, form)
        try:
            db.session.commit()
            flash('The new group is added, and you are set as a member of the new group')
            return redirect(request.referrer)
        except:
            db.session.rollback()
            flash('Could not create the group')

    return render_template('groups/group_create.html', form=form, parent=parent_group)


@groups_bp.route('/course_group/create/', methods=['POST', 'GET'])
@login_required
def create_course_group():
    """Create a group for a course
    """
    group_id = request.args.get('group_id')

    form = GroupForm(request.form)
    if request.method == 'POST' and form.validate():
        # Check whether the group name is not empty
        if form.name.data == '':
            flash('The group name can not be empty!')
            raise Exception('The group name could not be empty')
        group_name = slugify(form.name.data, separator='_')

        # Check whether the group already exists
        parent_group = Group.query.filter_by(id=group_id).one_or_none()
        if group_name in [g.name for g in parent_group.children]:
            raise Exception('The group already exists.')

        new_group = new_group_to_db(group_name, parent_group, form)
        try:
            db.session.commit()
            flash('The new group is added,',
                  'and you are set as the admin of the new group')
        except:
            raise Exception('Could not create the group')

        return jsonify(group_id=new_group.id,
                       group_slug=group_slugify(new_group.name, new_group.parent))
    else:
        raise Exception("Error occur")


# -------------------------------------------------------------------------------------------------#
# Group management

@groups_bp.route('delete/<group_id>/', methods=['POST'])
# @groups_bp.route('delete/', methods=['POST'])
@login_required
@role_permission.require(http_exception=403)
@group_manage_perm
def delete_group(group_id, **kwargs):
    """Delete a group
    """
    group = kwargs['group']

    courses = (db.session.query(CourseInstance)
               .filter(CourseInstance.owners.any(id=group.id)).all())

    if courses:
        error_message = dumps({'message': 'You need to remove the courses to another group'})
        abort(Response(error_message, 406))

    try:
        db.session.delete(group)
        db.session.commit()
    except:
        db.session.rollback()
        logging.info('rollback')
        error_message = dumps({'message': 'Error occurs and could not remove the group'})
        abort(Response(error_message, 501))

    return jsonify(status='success')


@groups_bp.route('edit/<group_id>/', methods=['GET', 'POST'])
@login_required
@role_permission.require(http_exception=403)
@group_manage_perm
def edit_group(group_id, **kwargs):
    if 'group' in kwargs:
        group = kwargs['group']
    else:
        group = db.session.query(Group).filter_by(id=group_id).one_or_none()

    group_slug = group_slugify(group.name, group.parent)
    permissions = [perm.type.name for perm in group.permissions]
    form = GroupForm(request.form)
    form.name.label = "New group name"
    form.parent_path.label = "New parent path"
    form.permissions.label = 'Update permission'

    if request.method == 'POST' and form.validate():
        # Edit the group name
        if request.form['edit'] == 'name':
            new_name = slugify(form.name.data, separator='_')

            # Check whether the name is unchanged
            if new_name == group.name:
                flash('No changes to make for the group')
                return redirect(url_for('.edit_group', group_id=group.id))

apluslms_shepherd/repos/views.py
import logging

from flask import Blueprint, render_template
from flask_login import login_required, current_user

from apluslms_shepherd.groups.utils import role_permission
from apluslms_shepherd.repos.models import GitRepository

repo_bp = Blueprint('repos', __name__, url_prefix='/repos/')
logger = logging.getLogger(__name__)


@repo_bp.route('', methods=['GET'])
@login_required
@role_permission.require(http_exception=403)
def list_repos():
    all_repos = GitRepository.query.all()
    return render_template('repos/repo_list.html', user=current_user, repos=all_repos)

apluslms_shepherd/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from apluslms_shepherd.build.models import Build
from apluslms_shepherd.courses.models import CourseInstance

main_bp = Blueprint('main', __name__)


class FrontendBuild(object):
    def __init__(self, course_id, number, course_key, instance_key, result):
        self.course_id = course_id
        self.instance_key = instance_key
        self.course_key = course_key
        self.number = number
        self.current_result = None if result is None else result.name


@main_bp.route('/', methods=['GET'])
@login_required
def main_page():
    instances = CourseInstance.query.all()
    sorted_build_entries = Build.query.order_by(Build.number.desc())
    newest_builds = [
        FrontendBuild(course_id=instance.id,
                      instance_key=instance.instance_key,
                      course_key=instance.course_key,
                      number=0 if len(sorted_build_entries.filter_by(course_id=instance.id).all()) is 0
                      else sorted_build_entries.filter_by(course_id=instance.id).first().number,
                      result=None if len(sorted_build_entries.filter_by(course_id=instance.id).all()) is 0
                      else sorted_build_entries.filter_by(course_id=instance.id).first().result,
                      )
        for instance in instances
    ]
    return render_template('main.html', user=current_user, instances=newest_builds)

apluslms_shepherd/templates/groups/groupPerm_manage.html
{% extends 'base.html' %}
{% block title %}
    Manage parent groups
{% endblock %}
{% block head %}
<script src="{{ url_for('static', filename='are_you_sure.js') }}"></script>
{% endblock %}
{% block body %}
<div id='possible_parents' style = "float:left;width:50%;font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
    <div class="centered">
        <strong>Add Parent Groups</strong>
        <ul>
            {%- for group1,slug1 in possible_parents %}
            <li class="form-inline">
            {{slug1}} &nbsp; &nbsp;
            <form method="post" action="{{ url_for('groups.add_create_group_perm', group_id=group_id) }}"> 
                <button type="submit" id='add_perm' name='new_parent' value={{group1.id}} class="btn btn-outline-danger are-you-sure">Set</button>
            </form> 
            </li>
            {% endfor %} 
        </ul>
    </div>
</div>


<div id='parents' style = "float:right;width:50%;font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
    <div class="centered">
    <strong> Parent Groups</strong>
    <ul>
        {%- for group2,slug2 in parents %}
        <li class="form-inline">
        {{slug2}} &nbsp; &nbsp;
        <form method="post" action="{{ url_for('groups.del_create_group_perm', group_id=group_id) }}"> 
            <button type="submit" id='del_perm' name='del_parent' value={{group2.id}} class="btn btn-outline-danger are-you-sure">Remove</button>
        </form> 
        </li>
        {% endfor %} 
    </ul>
</div>
</div>

{% endblock %}

apluslms_shepherd/templates/groups/group_create.html
{% extends 'base.html' %}
{% block head %}
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.js"></script>
<script src="{{ url_for('static', filename='helpers.js') }}"></script>

<script>
$(function(){  
$("#permissions-self_admin").prop('checked', true);
});
</script>

<script>
$(function() {
// Get the form fields and hidden div
var checkbox = $("#permissions-courses");
var hidden = $("#div_course_prefix");

// Hide the fields.
hidden.hide();

// Setup an event listener for when the state of the 
// checkbox changes.
checkbox.change(function() {
  // Check to see if the checkbox is checked.
  // If it is, show the fields and populate the input.
  // If not, hide the fields.
  if (checkbox.is(':checked')) {
    // Show the hidden fields.
    hidden.show();
  } else {
    // Make sure that the hidden fields are indeed
    // hidden.
    hidden.hide();
  }
});
});  
</script>

{% endblock %}

{% block title %}
    Add New group
{% endblock %}

{% block body %}
    <div class="container text-center">
        {% from "_formhelpers.html" import render_field %}
        <form id='group_form' method=post >
            <dl class="form-group">
                {{ render_field(form.name, class='form-control') }}
                {% if not parent %}
                {{ render_field(form.parent_path, class='form-control') }}
                {% endif %}
                {{ render_field(form.permissions) }}
                <div id="div_course_prefix">
                    {{ render_field(form.course_prefix, class='form-control') }}
                </div>
            </dl>
            {% block button %}
                <p><input type=submit class="btn-lg btn-outline-primary " value=Create>
                    <input type="button" onclick="location.href='/groups/'" class="btn-lg btn-outline-secondary "
                           value=Cancel>
                </p>
            {% endblock %}
        </form>
    </div>
{% endblock %}

apluslms_shepherd/templates/groups/group_edit.html
{% extends 'base.html' %}
{% block title %}
    Edit group
{% endblock %}

{% block body %}
    <div class="container text-center">
        {% from "_formhelpers.html" import render_field %}
        <div>Group: <strong>{{ group_slug }}</strong></div>
        <form method="POST">
                <dl class="form-group">
                    <dd>
                        {{ form.name.label }} {{ form.name }} 
                        <button type="submit" class="btn btn-outline-danger are-you-sure" 
                        name="edit" value="name"> Rename </buttton>
                    </dd>
                    <dd>
                        {{ form.parent_path.label }} {{ form.parent_path}} 
                        <button type="submit" class="btn btn-outline-danger are-you-sure" 
                        name="edit" value="parent path"> Update parent path </buttton>
                    </dd>
                    <dd>
                        <ul>
                        {{ form.permissions.label }} {{ form.permissions}} 
                        </ul>   
                        <button type="submit" class="btn btn-outline-danger are-you-sure" 
                        name="edit" value="permissions"> Update permissions </buttton>
                    </dd>
                    <div id="div_course_prefix">
                        {{ render_field(form.course_prefix, class='form-control') }}
                    </div>
                    <div id='div_update_course_prefix'>
                        <button type="submit" class="btn btn-outline-danger are-you-sure" 
                        name="edit" value="course prefix"> Update course prefix </buttton>
                    </div>
                    <div id='div_parent_groups'>
                        <button class="btn btn-outline-danger are-you-sure" 
                        onclick="location.href='/groups/{{group_id}}/parents/'" > Manage parents of subgroups </buttton>
                    </div>
                </dl>
        </form>
    </div>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='are_you_sure.js') }}"></script>
<script>
$(function() {
var permissions = {{permissions|tojson|safe }};
var checkbox = $("#permissions-courses");
var hidden = $("#div_course_prefix");
var hidden_button = $("#div_update_course_prefix");

hidden.hide();
hidden_button.hide();
if (permissions.includes('courses')){
    hidden.show();
    hidden_button.show();
}else{
    checkbox.change(function() {
    if (checkbox.is(':checked')) {
    hidden.show();
    } else {
    hidden.hide();
    }});
};  

if (permissions.includes('subgroups')){
    $("#div_parent_groups").show();
}else{
    $("#div_parent_groups").hide();
};  
});  
</script>

{% endblock %}

apluslms_shepherd/templates/groups/group_list.html
{% extends 'base.html' %}

{% block title %}
    Group list
{% endblock %}
{% block head %}
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.js"></script>
<script src="{{ url_for('static', filename='helpers.js') }}"></script>

<link href="{{ url_for('static', filename='group_list.css') }}" rel="stylesheet" type="text/css">

<script>
     $(function () {
    $('.tree li:has(ul)').addClass('parent_li').find(' > span').attr('title', 'Collapse this branch');
    $('.tree li.parent_li > span').on('click', function (e) {
        var children = $(this).parent('li.parent_li').find(' > ul > li');
        if (children.is(":visible")) {
            children.hide('fast');
            $(this).attr('title', 'Expand this branch').find(' > i').addClass('icon-plus-sign').removeClass('icon-minus-sign');
        } else {
            children.show('fast');
            $(this).attr('title', 'Collapse this branch').find(' > i').addClass('icon-minus-sign').removeClass('icon-plus-sign');
        }
        e.stopPropagation();
    });
    
    $(".start-closed").click();
});
</script>
<script>
$('.tree ul').hide();

$('.check').change(function() {
    if (checkbox.is(':checked')){
        $(this).find('ul').slideToggle();
    }
   
});
</script>

{% endblock %}
{% block body %}
<h1 style = "font-size:50px;">
        <strong>{{title}}</strong>
        {%if node %}
            <button type="button" class="btn btn-outline-primary"
            onclick="goBack()">Return 
            </button>
            <button type="button" class="btn btn-outline-primary"
            onclick="location.href='/groups/{{ node.id }}/create/'">Create subgroup 
            </button>
        {% else %}
        <button type="button" class="btn btn-outline-primary"
        onclick="location.href='/groups/create/'">Create group 
        </button>
        {% endif %}
</h1>
    
    <div class='tree' style = "font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
        
            {%- for group in roots recursive %}
            <ul>
            {% if group.level==1 %}
            <li><span ><i class="icon-folder-open"></i>
            {% elif not group.children %}
            <li><span ><i class="icon-leaf"></i>
            {% else %}
            <li><span ><i class="icon-minus-sign"></i>
            {% endif %} 
            <input class='check' type="checkbox" />
            {{group.name}}</span>
            <button type="button" class="btn btn-outline-primary"
            onclick="location.href='/groups/{{ group.id }}/members/'">Members
            </button>
            <button type="button" class="btn btn-outline-primary"
            onclick="location.href='/groups/{{ group.id }}/subgroups/'">Subgroups
            </button>
            </li>
            {%- if group.children -%}
                {{ loop(group.children) }}
            {%- endif %}
            </ul>
            {%- endfor %}
            
    </div>

{% endblock %}

apluslms_shepherd/templates/groups/move_courses.html
<div class="modal fade" id="moveCourseModal" tabindex="-1" role="dialog" aria-labelledby="moveCourseModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Remove courses</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id='owner_form'>
                <div class="modal-body">
                    <dl class="form-group">
                        <dt><label for="parent_group">New owner</label>
                            <dd><select  class="form-control" id="new_owner"><option value="-1">---</option></select>
                            </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="move_courses" class="btn btn-outline-danger are-you-sure" >Submit</button>
                </div>
            </form>
            </div>
        </div>
    </div>

apluslms_shepherd/templates/groups/my_groups.html
{% extends 'base.html' %}
{% block title %}
    Group list
{% endblock %}

{% block body %}
<h1 style = "font-size:50px;">
        <strong>{{title}}</strong>
</h1>
    
    <div  style = "font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
        <ul>
            {%- for group,slug in groups %}
            <li class='group' value={{group.id}}>
            {{slug}} <br>
            <form class="delete_form" value={{ group.id }} method="post" action="{{ url_for('groups.delete_group', group_id=group.id) }}"> 
                    <button type="button" class="btn btn-outline-primary"
                    onclick="location.href='/groups/{{ group.id }}/members/'">Members
                    </button>
                    <button type="button" class="btn btn-outline-primary"
                    onclick="location.href='/groups/{{ group.id }}/subgroups/'">Subgroups
                    </button>
                    <button type="button" class="btn btn-outline-primary"
                    onclick="location.href='/groups/edit/{{ group.id }}/'">Edit
                    </button>
                    <button type="button" class="btn btn-outline-primary"
                    onclick="location.href='/groups/{{group.id }}/create/'">New subgroup 
                    </button>
                    <button name='delete_btn' value={{ group.id }} type="submit" class="btn btn-outline-danger are-you-sure delete">Delete</button> 
            </form>
            </li>
            {% endfor %} 
        </ul>
    </div>
{% include 'groups/move_courses.html' %}
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='are_you_sure.js') }}"></script>
<script src="{{ url_for('static', filename='my_groups.js') }}"></script>
{% endblock %}